/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-11-28 20:23:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import finalproject.bookstore.*;
import java.util.*;

public final class BranchWeb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"back12.jpg\">\r\n");
      out.write("\t<h1>Branch Store</h1>\r\n");
      out.write("\r\n");

	BranchDAO dao = new BranchDAO();
	
	//controller{
	String action = request.getParameter("action");
    String name = request.getParameter("name");
    String saleprice = request.getParameter("saleprice");
    String stock = request.getParameter("stock");
    String version = request.getParameter("version");
    String action2 = request.getParameter("action2");
    String name2 = request.getParameter("name2");
    String saleprice2 = request.getParameter("saleprice2");
    String stock2 = request.getParameter("stock2");
    String version2 = request.getParameter("version2");
    Branch app = new Branch();
    Branch apB2 = new Branch();
    
    if("create".equals(action)){
    	int stockInt = Integer.parseInt(stock);
    	double salepriceD = Double.parseDouble(saleprice);
    	int versionInt = Integer.parseInt(version);
    	app = new Branch(salepriceD, stockInt, name, versionInt);
    	dao.create(app);
    }else if("remove".equals(action)){
    	int versionInt = Integer.parseInt(version);
    	dao.remove(name,versionInt);
    }else if("select".equals(action)){
    	int versionInt = Integer.parseInt(version);
    	app = dao.selectOne(name,versionInt);
    }else if("update".equals(action)){
    	int stockInt = Integer.parseInt(stock);
    	double salepriceD = Double.parseDouble(saleprice);
    	int versionInt = Integer.parseInt(version);
        app = new Branch(salepriceD, stockInt,name,versionInt); 
    	dao.update(name,versionInt, app);
    }else if("create2".equals(action)){
    	int stockInt = Integer.parseInt(stock);
    	double salepriceD = Double.parseDouble(saleprice);
    	int versionInt = Integer.parseInt(version);
        app = new Branch(salepriceD, stockInt,name,versionInt); 
    	int stockInt2 = Integer.parseInt(stock2);
    	double salepriceD2 = Double.parseDouble(saleprice2);
    	int versionInt2 = Integer.parseInt(version2);
        apB2 = new Branch(salepriceD2, stockInt2,name2,versionInt2); 
		List<Branch> twoInputs = new ArrayList<Branch>();
		twoInputs.add(app);
		twoInputs.add(apB2);
		dao.listInsert(twoInputs);
    }
    	
    	
    	
	//Seller app1 = new Seller("xxxyxx", 8.99);
	//dao.create(app1);
	
	
	List<Branch> branchs = dao.selectAll();
	 //}

      out.write(" \r\n");
      out.write("<form action=\"BranchWeb.jsp\">\r\n");
      out.write("\t<table class= \"table\">\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t<td>stock for bookstore:</td>\r\n");
      out.write("\t\t\t<td>name for bookstore:</td>\r\n");
      out.write("\t\t\t<td>price for bookstore:</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td><input name=\"stock\" class=\"form-control\" value=\"");
      out.print( app.getStock());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td><input name=\"name\" class=\"form-control\" value=\"");
      out.print( app.getName());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td><input name=\"saleprice\" class=\"form-control\" value=\"");
      out.print( app.getSaleprice());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td><input name=\"version\" type='hidden' class=\"form-control\" value=\"");
      out.print( app.getVersion());
      out.write("\"/></td>\t\t\t\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-success\" name=\"action\" value=\"create\">\r\n");
      out.write("\t\t\t\t\tAdd\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" name=\"action\" value=\"update\">\r\n");
      out.write("\t\t\t\t\tUpdate Stock or Price\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("<tr>\t\r\n");
      out.write("\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td><input name=\"stock2\" class=\"form-control\" value=\"");
      out.print( apB2.getStock());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td><input name=\"name2\" class=\"form-control\" value=\"");
      out.print( apB2.getName());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td><input name=\"saleprice2\" class=\"form-control\" value=\"");
      out.print( apB2.getSaleprice());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t<td><input name=\"version2\" type='hidden' class=\"form-control\" value=\"");
      out.print( apB2.getVersion());
      out.write("\"/></td>\t\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-success\" name=\"action\" value=\"create2\">\r\n");
      out.write("\t\t\t\t\tAdd 2 books together into Branch store\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
 for(Branch ap:branchs){	

      out.write("  <tr>\r\n");
      out.write("\t\t<td>");
      out.print( ap.getStock() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print( ap.getName() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print( ap.getSaleprice() );
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print( ap.getVersion() );
      out.write("</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<a class=\"btn btn-danger\" href=\"BranchWeb.jsp?action=remove&name=");
      out.print( ap.getName() );
      out.write("&version=");
      out.print( ap.getVersion() );
      out.write("\">\r\n");
      out.write("\t\t\t\tDelete\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<a class=\"btn btn-warning\" href=\"BranchWeb.jsp?action=select&name=");
      out.print( ap.getName() );
      out.write("&version=");
      out.print( ap.getVersion() );
      out.write("\">\r\n");
      out.write("\t\t\t\tSelect\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
 
	}

      out.write("\t\r\n");
      out.write("   </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
