/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-11-28 17:38:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import finalproject.bookstore.*;
import java.util.*;

public final class BuyerWeb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"back6.jpg\">\r\n");
      out.write("\t<h1>Welcome to Book Store</h1>\r\n");
      out.write("\r\n");

	BranchDAO dao = new BranchDAO();
	
	//controller{
	String action = request.getParameter("action");
    String name = request.getParameter("name");
    String saleprice = request.getParameter("saleprice");
    String stock = request.getParameter("stock");
    String orderNbr = request.getParameter("orderNbr");
    String version = request.getParameter("version");
    String action2 = request.getParameter("action2");
    String name2 = request.getParameter("name2");
    String saleprice2 = request.getParameter("saleprice2");
    String orderNbr2 = request.getParameter("orderNbr2");
    String stock2 = request.getParameter("stock2");
    String version2 = request.getParameter("version2");
    Branch app = new Branch();
    String order1 = request.getParameter("options");
    String order2 = request.getParameter("options2");
    Order ap1 = new Order();
    Order ap2 = new Order();
	String orderStatus = "Please click the order button to make an order";
    
    if("order".equals(action)){
		String[] valuesplit1 = order1.split(",");
		//System.out.println(valuesplit1[1]);
		//System.out.println(valuesplit1[2]);
		//System.out.println(valuesplit1[0]);
     	int orderNbrInt = Integer.parseInt(orderNbr);
    	int versionInt = Integer.parseInt(valuesplit1[2]);
     	int stockInt = Integer.parseInt(valuesplit1[0]);
     	name = valuesplit1[1];
        ap1 = new Order(orderNbrInt, stockInt,name,versionInt); 
        
		String[] valuesplit2 = order2.split(",");
     	int orderNbrInt2 = Integer.parseInt(orderNbr2);
    	int versionInt2 = Integer.parseInt(valuesplit2[2]);
     	int stockInt2 = Integer.parseInt(valuesplit2[0]);
     	name2 = valuesplit2[1];
        ap2 = new Order(orderNbrInt2, stockInt2,name2,versionInt2); 

		List<Order> twoInputs = new ArrayList<Order>();
		twoInputs.add(ap1);
		twoInputs.add(ap2);
		orderStatus = dao.listOrder(twoInputs);
		//app = options.getName();
		//System.out.println("hellooooooooooooooo");

    }
    	

    	
	//Seller app1 = new Seller("xxxyxx", 8.99);
	//dao.create(app1);
	
	
	List<Branch> branchs = dao.selectAll();
	 //}

      out.write(" \r\n");
      out.write("    \t<td> ");
      out.print( orderStatus );
      out.write("\r\n");
      out.write("    \t</td>\r\n");
      out.write("<form action=\"BuyerWeb.jsp\">\r\n");
      out.write("\r\n");
      out.write("\t<table class= \"table\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<td> <select name = \"options\">\r\n");
      out.write("\t\t\t\t");
 for(Branch apa:branchs){
      out.write("  \r\n");
      out.write("\t\t\t\t\t\t<option value = \"");
      out.print(apa.getStock());
      out.write(',');
      out.print(apa.getName());
      out.write(',');
      out.print(apa.getVersion());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( apa.getName() );
      out.write(" -- Price:$");
      out.print( apa.getSaleprice() );
      out.write(" -- only ");
      out.print( apa.getStock() );
      out.write(" left\r\n");
      out.write("\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t");
 }
      out.write("\t\t\r\n");
      out.write("\t\t\t</select> \t</td>\t\t\r\n");
      out.write("\t\t\t<td><input name=\"orderNbr\" class=\"form-control\" value=\"");
      out.print( ap1.getOrderNbr());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<td> <select name = \"options2\">\r\n");
      out.write("\t\t\t\t");
 for(Branch apa:branchs){
      out.write("  \r\n");
      out.write("\t\t\t\t\t\t<option value = \"");
      out.print(apa.getStock());
      out.write(',');
      out.print(apa.getName());
      out.write(',');
      out.print(apa.getVersion());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( apa.getName() );
      out.write(" -- Price:$");
      out.print( apa.getSaleprice() );
      out.write(" -- only ");
      out.print( apa.getStock() );
      out.write(" left\r\n");
      out.write("\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t");
 }
      out.write("\t\t\r\n");
      out.write("\t\t\t</select> \t</td>\t\t\r\n");
      out.write("\t\t\t<td><input name=\"orderNbr2\" class=\"form-control\" value=\"");
      out.print( ap2.getOrderNbr());
      out.write("\"/></td>\r\n");
      out.write("\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-success\" name=\"action\" value=\"order\">\r\n");
      out.write("\t\t\t\t\torder\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("   </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
